### ISSUE TITLE
Document checklist

### ISSUE THREAD

**Issue by mandresm** [esm-tools/esm_tools#35]
Checklist from Sebastian (Geomar):

- [ ]     Document the variables you rely on e.g. base_dir, model_dir, …

- [x]  Document how the _in_work, _sources and _files things work e.g. how config_files, config_sources, config_in_work play together.

- [x]  Document with examples how add_ blocks work. E.g. just found out that you can combine namelist_changes and add_namelist_changes...

- [x] Document how choose_ blocks work. I still haven’t fully understood it, because it sometimes works and sometime’s not.

- [ ] Document how the environment_changes block works

- [ ] Document which yaml file overwrites the other

- [ ] What does the namelist entry do in a yaml file? Tell the parser to treat this config file as namelist?

- [x] Document the directory structure, I find it confusing where to look if you debug a run: expid/run_xxxx/scripts/*log, expid/scripts/*.log where the files are moved to at some point after the run. I personally find the duplication of the whole directory structure from expid/ into expid/run_xxxxxx/ very confusing. File lists (which are also kind of log files) end up in expid/config/. Maybe it get’s better if documented.

- [ ] Document what’s not allowed, e.g. having multiple input_sources entries in choose blocks as they are overwrite each other (see also 6.) 

- [ ] Why do some yaml’s have general blocks and some not (e.g. echam.yaml) i.e. document the role of the general blocks.

**Comment by mandresm** [comment]
Information about the experiment directory structure added to the user manual in the develop branch. The new sections can be read in:

[https://esm-tools.readthedocs.io/en/develop/esm_runscripts.html](url)

**Comment by mandresm** [comment]
This issue has been opened now for quite some time. Since most of the docummentation requests of the ECHAM meeting go in line with what @seb-wahl reported here, I added this to the ECHAM project, so that it gets done soon.

**Comment by dbarbi** [comment]
moved to trello board
